version: "3.1"
volumes:
  postgres: ~
services:
  nginx:
    image: nginx:alpine
    working_dir: /app
    volumes:
      - ${PWD}:/app
      - ./docker/hosts/app.conf:/etc/nginx/conf.d/default.conf
      - ./docker/hosts/symfony:/etc/nginx/symfony
    ports:
      - "${NGINX_PORT}:81"
    links:
      - php
  postgres:
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
  php:
    build: docker/images/php
    working_dir: /app
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ${PWD}:/app
      - ${HOME}/.composer:/.composer
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    links:
      - postgres
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    ports:
            - "5672:5672"
            - "15672:15672"
    networks:
        - rabbitmq_go_net

  node:
    image: node:alpine
    environment:
      - YARN_CACHE_FOLDER=${PWD}:/.yarn
    working_dir: /app
   # user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ${PWD}:/app
      - ${HOME}/.yarn:/yarn
networks:
  rabbitmq_go_net:
    driver: bridge
